### ISSUE TITLE
Editions query are wrong

### ISSUE THREAD

**Issue by onmax** [DA-ETSIINF/TryIT#14]
Error while loading activities page. 
``python manage.py migrate`` didn't work

![error1](https://user-images.githubusercontent.com/22072217/37096730-dcfa34ce-2219-11e8-9297-0b6be7365270.PNG)
![error2](https://user-images.githubusercontent.com/22072217/37096764-fc345522-2219-11e8-8a65-6fe2cc953e4d.PNG)

**Comment by VictorNS69** [comment]
I close this issue because the problem is that you have no DB locally, so the query's fails all the time.

At this time, you should have access to our testing DB.
