### ISSUE TITLE
Create the README.md file

### ISSUE THREAD

**Issue by svg153** [DA-ETSIINF/TryIT#15]
TODO list to include in the `README.md`
- [x] Description (in one line)
- [ ] Travis CI
- [x] Dependecies
- [x] Installation
  - [x] Linux
  - [x] Mac
  - [x] Windows
  - [x] Docker
- [ ] Run
  - [x] DDBB
    - [x] Crete from scrach
    - [ ] Insert examples
  - [x] Linux (terminal)
  - [x] Windows (terminal)
  - [ ] PyCharm
    - [ ] Normal
    - [x] Docker
- [x] License
- [x] Authors

**Comment by VictorNS69** [comment]
To join the project and understand all the work you have done, I would like to solve this issue and make the needed relevant information for this repository.

**Comment by VictorNS69** [comment]
@svg153 @alvarogtx300 Most of the items you want in the `README.md` are already written,
 those that aren't I really don know how to write it.

If you think that the work done by me is enough, I can create a pull request. If you think I should improve any paragraph, just tell me.

For now I think it's enough for the project.

**Comment by alvarogtx300** [comment]
I think that it's enough for the moment.
You can create a pull request.

**Comment by onmax** [comment]
#95
