### ISSUE TITLE
Frontend VUEJS and API recode

### ISSUE THREAD

**Issue by mdmoreno** [DA-ETSIINF/TryIT#172]
In order to have a more adaptable web, and implement the api, we need a new frontend.  We will use Vue JS framework. At the same time all views must be coded as api

TO DO:
- First thing to do is create an scheme with al the pages needes 
- Routing 
- API calls

**Comment by onmax** [comment]
This issue should be rename to API recode. The frontend will be saved in other repository so we can handle issues, to-do lists, tags... indepently
