### ISSUE TITLE
Add page to search the number of credits 

### ISSUE THREAD

**Issue by onmax** [DA-ETSIINF/TryIT#43]

**Comment by onmax** [comment]
Note: Add a link in the footer

**Comment by svg153** [comment]
> Note: Add a link in the footer

Better in NavBar when the event has finished.

**Comment by onmax** [comment]
Ok, so in call for papers in footer and during the event in top

**Comment by svg153** [comment]
@onmax ok. But do it automatically depending on the variables

**Comment by onmax** [comment]
[PR62](https://github.com/DA-ETSIINF/TryIT/pull/62)
